esercizio: esercizio.o funzioni.o
	g++ esercizio.o funzioni.o -o esercizio.x
esercizio.o: funzioni.h
	g++ -c esercizio1.2.cpp -o esercizio.o
funzioni.o: funzioni.cpp funzioni.h
	g++ -c funzioni.cpp -o funzioni.o